const COMPANIES = {
  GET_COMPANIES_SUCCESS: "GET_COMPANIES_SUCCESS",
  GET_COMPANIES_ERROR: "GET_COMPANIES_ERROR",
  ADD_COMPANY_SUCCESS: "ADD_COMPANY_SUCCESS",
  ADD_COMPANY_ERROR: "ADD_COMPANY_ERROR",
  DELETE_COMPANY_SUCCESS: "DELETE_COMPANY_SUCCESS",
  DELETE_COMPANY_ERROR: "DELETE_COMPANY_ERROR",
  EDIT_COMPANY_SUCCESS: "EDIT_COMPANY_SUCCESS",
  EDIT_COMPANY_ERROR: "EDIT_COMPANY_ERROR",
  ADD_EXISTING_COMPANY_SUCCESS: "ADD_EXISTING_COMPANY_SUCCESS",
  ADD_EXISTING_COMPANY_ERROR: "ADD_EXISTING_COMPANY_ERROR",
  DELETE_EXISTING_COMPANY_SUCCESS: "DELETE_EXISTING_COMPANY_SUCCESS",
  DELETE_EXISTING_COMPANY_ERROR: "DELETE_EXISTING_COMPANY_ERROR",
};

export default COMPANIES;
