const USER = {
  USER_SIGIN_SUCCESS: "USER_SIGIN_SUCCESS",
  USER_SIGNIN_ERROR: "USER_SIGNIN_ERROR",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_ERROR: "USER_SIGNUP_ERROR",
};

export default USER;
